/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiAdvisorRouteImport } from './routes/ai-advisor'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as IpoAllotmentCalculatorRouteImport } from './routes/ipo-allotment-calculator'
import { Route as IpoAllotmentStatusRouteImport } from './routes/ipo-allotment-status'
import { Route as IpoCalendarRouteImport } from './routes/ipo-calendar'
import { Route as IpoGmpListRouteImport } from './routes/ipo-gmp-list'
import { Route as IpoListingGainCalculatorRouteImport } from './routes/ipo-listing-gain-calculator'
import { Route as IpoPerformanceRouteImport } from './routes/ipo-performance'
import { Route as IpoSubscriptionStatusRouteImport } from './routes/ipo-subscription-status'
import { Route as MarketNewsRouteImport } from './routes/market-news'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UpcomingIpoRouteImport } from './routes/upcoming-ipo'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdvisorIdRouteImport } from './routes/advisor/$id'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as IpoIdRouteImport } from './routes/ipo/$id'
import { Route as ApiPublicHooksIpoAlertsRouteImport } from './routes/api/public/hooks/ipo-alerts'
import { Route as ApiPublicHooksWeeklyBlogRouteImport } from './routes/api/public/hooks/weekly-blog'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAdvisorRoute = AiAdvisorRouteImport.update({
  id: '/ai-advisor',
  path: '/ai-advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const IpoAllotmentCalculatorRoute = IpoAllotmentCalculatorRouteImport.update({
  id: '/ipo-allotment-calculator',
  path: '/ipo-allotment-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IpoAllotmentStatusRoute = IpoAllotmentStatusRouteImport.update({
  id: '/ipo-allotment-status',
  path: '/ipo-allotment-status',
  getParentRoute: () => rootRouteImport,
} as any)
const IpoCalendarRoute = IpoCalendarRouteImport.update({
  id: '/ipo-calendar',
  path: '/ipo-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IpoGmpListRoute = IpoGmpListRouteImport.update({
  id: '/ipo-gmp-list',
  path: '/ipo-gmp-list',
  getParentRoute: () => rootRouteImport,
} as any)
const IpoListingGainCalculatorRoute =
  IpoListingGainCalculatorRouteImport.update({
    id: '/ipo-listing-gain-calculator',
    path: '/ipo-listing-gain-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const IpoPerformanceRoute = IpoPerformanceRouteImport.update({
  id: '/ipo-performance',
  path: '/ipo-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const IpoSubscriptionStatusRoute = IpoSubscriptionStatusRouteImport.update({
  id: '/ipo-subscription-status',
  path: '/ipo-subscription-status',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketNewsRoute = MarketNewsRouteImport.update({
  id: '/market-news',
  path: '/market-news',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UpcomingIpoRoute = UpcomingIpoRouteImport.update({
  id: '/upcoming-ipo',
  path: '/upcoming-ipo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorIdRoute = AdvisorIdRouteImport.update({
  id: '/advisor/$id',
  path: '/advisor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IpoIdRoute = IpoIdRouteImport.update({
  id: '/ipo/$id',
  path: '/ipo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksIpoAlertsRoute = ApiPublicHooksIpoAlertsRouteImport.update({
  id: '/api/public/hooks/ipo-alerts',
  path: '/api/public/hooks/ipo-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksWeeklyBlogRoute =
  ApiPublicHooksWeeklyBlogRouteImport.update({
    id: '/api/public/hooks/weekly-blog',
    path: '/api/public/hooks/weekly-blog',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-advisor': typeof AiAdvisorRoute
  '/compare': typeof CompareRoute
  '/disclaimer': typeof DisclaimerRoute
  '/ipo-allotment-calculator': typeof IpoAllotmentCalculatorRoute
  '/ipo-allotment-status': typeof IpoAllotmentStatusRoute
  '/ipo-calendar': typeof IpoCalendarRoute
  '/ipo-gmp-list': typeof IpoGmpListRoute
  '/ipo-listing-gain-calculator': typeof IpoListingGainCalculatorRoute
  '/ipo-performance': typeof IpoPerformanceRoute
  '/ipo-subscription-status': typeof IpoSubscriptionStatusRoute
  '/market-news': typeof MarketNewsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/upcoming-ipo': typeof UpcomingIpoRoute
  '/admin/login': typeof AdminLoginRoute
  '/advisor/$id': typeof AdvisorIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ipo/$id': typeof IpoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/api/public/hooks/ipo-alerts': typeof ApiPublicHooksIpoAlertsRoute
  '/api/public/hooks/weekly-blog': typeof ApiPublicHooksWeeklyBlogRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-advisor': typeof AiAdvisorRoute
  '/compare': typeof CompareRoute
  '/disclaimer': typeof DisclaimerRoute
  '/ipo-allotment-calculator': typeof IpoAllotmentCalculatorRoute
  '/ipo-allotment-status': typeof IpoAllotmentStatusRoute
  '/ipo-calendar': typeof IpoCalendarRoute
  '/ipo-gmp-list': typeof IpoGmpListRoute
  '/ipo-listing-gain-calculator': typeof IpoListingGainCalculatorRoute
  '/ipo-performance': typeof IpoPerformanceRoute
  '/ipo-subscription-status': typeof IpoSubscriptionStatusRoute
  '/market-news': typeof MarketNewsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/upcoming-ipo': typeof UpcomingIpoRoute
  '/admin/login': typeof AdminLoginRoute
  '/advisor/$id': typeof AdvisorIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ipo/$id': typeof IpoIdRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/api/public/hooks/ipo-alerts': typeof ApiPublicHooksIpoAlertsRoute
  '/api/public/hooks/weekly-blog': typeof ApiPublicHooksWeeklyBlogRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-advisor': typeof AiAdvisorRoute
  '/compare': typeof CompareRoute
  '/disclaimer': typeof DisclaimerRoute
  '/ipo-allotment-calculator': typeof IpoAllotmentCalculatorRoute
  '/ipo-allotment-status': typeof IpoAllotmentStatusRoute
  '/ipo-calendar': typeof IpoCalendarRoute
  '/ipo-gmp-list': typeof IpoGmpListRoute
  '/ipo-listing-gain-calculator': typeof IpoListingGainCalculatorRoute
  '/ipo-performance': typeof IpoPerformanceRoute
  '/ipo-subscription-status': typeof IpoSubscriptionStatusRoute
  '/market-news': typeof MarketNewsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/upcoming-ipo': typeof UpcomingIpoRoute
  '/admin/login': typeof AdminLoginRoute
  '/advisor/$id': typeof AdvisorIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ipo/$id': typeof IpoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/api/public/hooks/ipo-alerts': typeof ApiPublicHooksIpoAlertsRoute
  '/api/public/hooks/weekly-blog': typeof ApiPublicHooksWeeklyBlogRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-advisor'
    | '/compare'
    | '/disclaimer'
    | '/ipo-allotment-calculator'
    | '/ipo-allotment-status'
    | '/ipo-calendar'
    | '/ipo-gmp-list'
    | '/ipo-listing-gain-calculator'
    | '/ipo-performance'
    | '/ipo-subscription-status'
    | '/market-news'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/upcoming-ipo'
    | '/admin/login'
    | '/advisor/$id'
    | '/blog/$slug'
    | '/ipo/$id'
    | '/admin/'
    | '/blog/'
    | '/api/public/hooks/ipo-alerts'
    | '/api/public/hooks/weekly-blog'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-advisor'
    | '/compare'
    | '/disclaimer'
    | '/ipo-allotment-calculator'
    | '/ipo-allotment-status'
    | '/ipo-calendar'
    | '/ipo-gmp-list'
    | '/ipo-listing-gain-calculator'
    | '/ipo-performance'
    | '/ipo-subscription-status'
    | '/market-news'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/upcoming-ipo'
    | '/admin/login'
    | '/advisor/$id'
    | '/blog/$slug'
    | '/ipo/$id'
    | '/admin'
    | '/blog'
    | '/api/public/hooks/ipo-alerts'
    | '/api/public/hooks/weekly-blog'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/ai-advisor'
    | '/compare'
    | '/disclaimer'
    | '/ipo-allotment-calculator'
    | '/ipo-allotment-status'
    | '/ipo-calendar'
    | '/ipo-gmp-list'
    | '/ipo-listing-gain-calculator'
    | '/ipo-performance'
    | '/ipo-subscription-status'
    | '/market-news'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/upcoming-ipo'
    | '/admin/login'
    | '/advisor/$id'
    | '/blog/$slug'
    | '/ipo/$id'
    | '/admin/'
    | '/blog/'
    | '/api/public/hooks/ipo-alerts'
    | '/api/public/hooks/weekly-blog'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAdvisorRoute: typeof AiAdvisorRoute
  CompareRoute: typeof CompareRoute
  DisclaimerRoute: typeof DisclaimerRoute
  IpoAllotmentCalculatorRoute: typeof IpoAllotmentCalculatorRoute
  IpoAllotmentStatusRoute: typeof IpoAllotmentStatusRoute
  IpoCalendarRoute: typeof IpoCalendarRoute
  IpoGmpListRoute: typeof IpoGmpListRoute
  IpoListingGainCalculatorRoute: typeof IpoListingGainCalculatorRoute
  IpoPerformanceRoute: typeof IpoPerformanceRoute
  IpoSubscriptionStatusRoute: typeof IpoSubscriptionStatusRoute
  MarketNewsRoute: typeof MarketNewsRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UpcomingIpoRoute: typeof UpcomingIpoRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdvisorIdRoute: typeof AdvisorIdRoute
  BlogSlugRoute: typeof BlogSlugRoute
  IpoIdRoute: typeof IpoIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicHooksIpoAlertsRoute: typeof ApiPublicHooksIpoAlertsRoute
  ApiPublicHooksWeeklyBlogRoute: typeof ApiPublicHooksWeeklyBlogRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-advisor': {
      id: '/ai-advisor'
      path: '/ai-advisor'
      fullPath: '/ai-advisor'
      preLoaderRoute: typeof AiAdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipo-allotment-calculator': {
      id: '/ipo-allotment-calculator'
      path: '/ipo-allotment-calculator'
      fullPath: '/ipo-allotment-calculator'
      preLoaderRoute: typeof IpoAllotmentCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipo-allotment-status': {
      id: '/ipo-allotment-status'
      path: '/ipo-allotment-status'
      fullPath: '/ipo-allotment-status'
      preLoaderRoute: typeof IpoAllotmentStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipo-calendar': {
      id: '/ipo-calendar'
      path: '/ipo-calendar'
      fullPath: '/ipo-calendar'
      preLoaderRoute: typeof IpoCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipo-gmp-list': {
      id: '/ipo-gmp-list'
      path: '/ipo-gmp-list'
      fullPath: '/ipo-gmp-list'
      preLoaderRoute: typeof IpoGmpListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipo-listing-gain-calculator': {
      id: '/ipo-listing-gain-calculator'
      path: '/ipo-listing-gain-calculator'
      fullPath: '/ipo-listing-gain-calculator'
      preLoaderRoute: typeof IpoListingGainCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipo-performance': {
      id: '/ipo-performance'
      path: '/ipo-performance'
      fullPath: '/ipo-performance'
      preLoaderRoute: typeof IpoPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipo-subscription-status': {
      id: '/ipo-subscription-status'
      path: '/ipo-subscription-status'
      fullPath: '/ipo-subscription-status'
      preLoaderRoute: typeof IpoSubscriptionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-news': {
      id: '/market-news'
      path: '/market-news'
      fullPath: '/market-news'
      preLoaderRoute: typeof MarketNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upcoming-ipo': {
      id: '/upcoming-ipo'
      path: '/upcoming-ipo'
      fullPath: '/upcoming-ipo'
      preLoaderRoute: typeof UpcomingIpoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/$id': {
      id: '/advisor/$id'
      path: '/advisor/$id'
      fullPath: '/advisor/$id'
      preLoaderRoute: typeof AdvisorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipo/$id': {
      id: '/ipo/$id'
      path: '/ipo/$id'
      fullPath: '/ipo/$id'
      preLoaderRoute: typeof IpoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ipo-alerts': {
      id: '/api/public/hooks/ipo-alerts'
      path: '/api/public/hooks/ipo-alerts'
      fullPath: '/api/public/hooks/ipo-alerts'
      preLoaderRoute: typeof ApiPublicHooksIpoAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/weekly-blog': {
      id: '/api/public/hooks/weekly-blog'
      path: '/api/public/hooks/weekly-blog'
      fullPath: '/api/public/hooks/weekly-blog'
      preLoaderRoute: typeof ApiPublicHooksWeeklyBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAdvisorRoute: AiAdvisorRoute,
  CompareRoute: CompareRoute,
  DisclaimerRoute: DisclaimerRoute,
  IpoAllotmentCalculatorRoute: IpoAllotmentCalculatorRoute,
  IpoAllotmentStatusRoute: IpoAllotmentStatusRoute,
  IpoCalendarRoute: IpoCalendarRoute,
  IpoGmpListRoute: IpoGmpListRoute,
  IpoListingGainCalculatorRoute: IpoListingGainCalculatorRoute,
  IpoPerformanceRoute: IpoPerformanceRoute,
  IpoSubscriptionStatusRoute: IpoSubscriptionStatusRoute,
  MarketNewsRoute: MarketNewsRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UpcomingIpoRoute: UpcomingIpoRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdvisorIdRoute: AdvisorIdRoute,
  BlogSlugRoute: BlogSlugRoute,
  IpoIdRoute: IpoIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicHooksIpoAlertsRoute: ApiPublicHooksIpoAlertsRoute,
  ApiPublicHooksWeeklyBlogRoute: ApiPublicHooksWeeklyBlogRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
